name: hcms

services:
  postgres:
    image: postgres:16
    container_name: hcms
    restart: always

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hcms

    ports:
      - "5432:5432"

    volumes:
      - hcms_postgres_data:/var/lib/postgresql/data

volumes:
  hcms_postgres_data:
    external: true
    name: hcms2_postgres_data
