name: tragwerker

services:
  postgres:
    image: postgres:16
    container_name: tragwerker-db
    restart: always

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tragwerker

    ports:
      - "5435:5432"

    volumes:
      - tragwerker_postgres_data:/var/lib/postgresql/data

volumes:
  tragwerker_postgres_data:
