export const SITE_IMAGES = {
  heroHome: "/uploads/media/home-hero-wireframe.jpg",
  heroHomeWireframe: "/uploads/media/home-hero-wireframe.jpg",
  homePhilosophy1: "/site/bauen-im-bestand-1.jpg",
  homePhilosophy2: "/site/bauen-im-bestand-2.jpg",
  homeTragwerksplanung: "/site/stahlbeton-1.jpg",
  homeKompetenzen: "/site/stahlbeton-3.jpg",
  heroPlanning: "/site/stahlbeton-1.jpg",
  heroReview: "/site/abnahme.jpg",
  heroTeam: "/site/bauen-im-bestand-1.jpg",
  heroMenschen: "/uploads/media/menschen-hero-bg.png",
  heroProjects: "/uploads/media/aussegnungshalle-1-dea1df77.jpg",
  heroKompetenzen: "/site/stahlbeton-3.jpg",
  introCollaboration: "/site/bauen-im-bestand-1.jpg",
  introPrecision: "/site/bauueberwachung.jpg",
  projectFallback: "/uploads/media/fussgangerbrucke-ffb-3-c93b1a93.jpg",
  menuBackground: "/uploads/media/menu-bg-archiplan.png",
  stahlbeton1: "/site/stahlbeton-1.jpg",
  stahlbeton2: "/site/stahlbeton-2.jpg",
  stahlbeton3: "/site/stahlbeton-3.jpg",
  bauenImBestand1: "/site/bauen-im-bestand-1.jpg",
  bauenImBestand2: "/site/bauen-im-bestand-2.jpg",
  holzbau: "/site/holzbau.jpg",
  stahlbau: "/site/stahlbau.jpg",
  abnahme: "/site/abnahme.jpg",
  bauueberwachung: "/site/bauueberwachung.jpg",
  logoMark: "/site/logo-on-paper.png",
} as const;
